# Configures pytest
# This file is necessary to stop pytest from barking about the @pytest.mark.*
[pytest]
addopts = --ignore=apps/wwaw
filterwarnings =
    ignore::DeprecationWarning:pyhocon
markers =
     # Integration levels
    integration: integration tests
    integration_basic: basic integration tests
    integration_basic_coffee_finder_advanced: basic integration tests
    integration_basic_coffee_finder_advanced_e2e: basic integration e2e tests
    integration_industry: industry integration tests
    integration_experimental: experimental integration tests
    integration_industry_airline_policy: industry integration tests
    integration_agent_network_designer: integration tests for agent network designer
    integration_basic_music_nerd_pro: integration tests for music nerd pro
    integration_industry_airline_policy_web_search: industry integration tests for airline policy web search

asyncio_default_fixture_loop_scope = function
