---
name: Checkmarx One

permissions:
    contents: read
    security-events: write

on:
    schedule:
        # M-F at 3:00 am UTC (offset from neuro-san and neuro-san-ui)
        - cron: "0 3 * * 1-5"
    workflow_dispatch:

jobs:
    checkmarx-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              # v6.0.2
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
              with:
                  fetch-depth: 0

            - name: Run Checkmarx One scan
              # build-common 1.0.9
              uses: cognizant-ai-lab/build-common/actions/checkmarx-one@b14b3de23cb9aca02b2165e57542335e0c8f5304
              with:
                  base-uri: ${{ vars.CX_BASE_URI }}
                  cx-tenant: ${{ vars.CX_TENANT }}
                  cx-client-id: ${{ vars.CX_CLIENT_ID }}
                  cx-client-secret: ${{ secrets.CX_CLIENT_SECRET }}
